#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# If an API key is set we should use it over any password / username.
if [ -n "$PBS_API_KEY_SECRET" ]; then
    PBS_PASSWORD="${PBS_API_KEY_SECRET}"
fi

if [ -n "$PBS_API_KEY_NAME" ]; then
    PBS_USER="${PBS_API_KEY_NAME}"
fi

if [ -z "$PBS_USER" ]; then
    echo "Error: PBS_USER is not set. This variable is required, please ensure it is set, or set PBS_API_KEY_NAME."
    exit 1
fi

if [ -z "$PBS_ENDPOINT" ]; then
    echo "Error: PBS_ENDPOINT is not set. This variable is required, please ensure it is set."
    exit 1
fi

if [ -z "$PBS_DATASTORE" ]; then
    echo "Error: PBS_DATASTORE is not set. This variable is required, please ensure it is set."
    exit 1
fi

if [ -z "$PBS_PASSWORD" ]; then
    echo "Error: PBS_PASSWORD is not set. This variable is required, please ensure it is set, or set PBS_API_KEY_SECRET."
    exit 1
fi

# Default to self-hosted if variable is unset
HEALTHCHECKS_SELF_HOSTED="${HEALTHCHECKS_SELF_HOSTED:-true}" # Defaults to 'true' if unset.

# Set the ping subdirectory for self-hosted instances only
if [[ "${HEALTHCHECKS_SELF_HOSTED}" == "true" ]]; then
    PING_SUBDIR="${HEALTHCHECKS_PING_ENDPOINT_DIR:-ping}" # Defaults to 'ping' if unset.
else
    PING_SUBDIR=""
fi

# Construct Healthchecks URL if required variables are set
if [[ -n "${HEALTHCHECKSHOSTNAME// }" && -n "${HEALTHCHECKSUUID// }" ]]; then
    if [[ -n "$PING_SUBDIR" ]]; then
        HEALTHCHECKSURL="${HEALTHCHECKSHOSTNAME}/${PING_SUBDIR}/${HEALTHCHECKSUUID}"
    else
        HEALTHCHECKSURL="${HEALTHCHECKSHOSTNAME}/${HEALTHCHECKSUUID}"
    fi
    export HEALTHCHECKSURL
fi

export PBS_PASSWORD="${PBS_PASSWORD}"
export PBS_REPOSITORY="${PBS_USER}@${PBS_ENDPOINT}:${PBS_DATASTORE}"
