#!/usr/bin/with-contenv bash
#
if [ -z "${SMTP_HOST:-}" ]; then
    # Mail disabled - stay in foreground doing nothing
    while true; do
        sleep 3600
    done
fi

# Get rid of the noise
nullmailer-send >/dev/null 2>&1