#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# This script runs once as the container starts to get an immediate backup.

# Define a logging function to prefix output to the docker logs.
output_to_log() {
    while IFS= read -r line; do
        echo "[backup] $(date +"%Y-%m-%d %H:%M:%S") $line"
    done
}
# Redirect all subsequent command outputs to output_to_log
exec > >(output_to_log)

# Set up error handling
handle_error() {
    local exit_code="$?"
    echo -e "Error occurred (Exit code: $exit_code)"
    exit "$exit_code"
}
trap handle_error ERR

/etc/s6-overlay/s6-rc.d/backup/run_include