#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Raise limits before running PBS
ulimit -n 65536
ulimit -u 65536

source /etc/s6-overlay/s6-rc.d/backup/hooks_include

path_to_filename() {
    local path="$1"
    local path_no_trailing_slash="${path%/}"  # Remove the trailing slash, if any
    local path_no_first_slash="${path_no_trailing_slash#\/}"  # Remove the first slash
    local filename="${path_no_first_slash//\//-}"  # Replace slashes with dashes
    echo "${filename}"
}

lastrunfile="/tmp/pbs_client_lastrun"

# Note the first evaluation is key and will initiate backup if the user opts
# to allow the first backup or we're
if [ "$CRON_BACKUP_ONLY" = "0" ] || [ -e "${lastrunfile}" ]; then

    # Run pre backup user hooks
    [ -n "$PRE_HOOK_DIR" ] && run_hook_dir "$PRE_HOOK_DIR"

    BACKUP_DIRECTORIES=()
    # Iterate over each subdirectory under /backup and add its full path to the array
    for dir in /backups/*; do
        if [[ -d "$dir" ]]; then
            BACKUP_DIRECTORIES+=("$dir/")
        fi
    done

    # Print the contents of the array if this is first run only.
    if [ ! -e "${lastrunfile}" ]; then
        echo "## Detected backup directories:"
        echo -e "#"
        if [ ${#BACKUP_DIRECTORIES[@]} -eq 0 ]; then
            echo "# Nothing to backup."
        else
            for path in "${BACKUP_DIRECTORIES[@]}"; do
                echo -e "# $path"
            done
            echo -e "#\n"
        fi
    fi

    # Construct the directory target list with the proxmox-backup-client syntax.
    # This makes 1 .pxar file per path.
    TARGETS=""
    for dir in "${BACKUP_DIRECTORIES[@]}"; do
        TARGET=$(path_to_filename "$dir").pxar:$dir
        TARGETS="${TARGETS} ${TARGET}"
    done

    # Build the backup command we want to execute. 
    BACKUPCMD="proxmox-backup-client backup ${TARGETS}"

    if [ -n "$PBS_DATASTORE_NS" ]; then
        BACKUPCMD+=" --ns ${PBS_DATASTORE_NS}"
    fi

    if [ -n "$PBS_BACKUP_CMD_APPEND_EXTRA_OPTS" ]; then
        BACKUPCMD+=" ${PBS_BACKUP_CMD_APPEND_EXTRA_OPTS}"
    fi

    # Source the variables from the setup_check scripting include file.
    source /etc/s6-overlay/s6-rc.d/setup_check/run_include

    # Print out the repository and backup command on first run only.
    if [ ! -e "${lastrunfile}" ]; then
        echo -e "## Backing up to repository: \n# ${PBS_REPOSITORY}\n"
        echo -e "## Executing backup command: \n# ${BACKUPCMD}\n"
    fi

    if [ -n "$HEALTHCHECKSURL" ]; then
        curl -fsS -m 10 --retry 5 -o /dev/null $HEALTHCHECKSURL/start
    fi

    # Run the actual backup command.
    ${BACKUPCMD} 2>&1
    BACKUP_EXIT_CODE=$?

    # Run post backup user hooks
    if [ "${BACKUP_EXIT_CODE}" -eq 0 ]; then
        [ -n "$POST_HOOK_DIR" ] && run_hook_dir "$POST_HOOK_DIR"
    else
        echo "Backup failed, skipping post hooks"
    fi

    # First run touches the file. Backups will set the date.
    echo "$(date +"%Y-%m-%d %H:%M:%S")" > "${lastrunfile}"

    # Only attempt email if SMTP_HOST is defined and not empty
    if [ -n "${SMTP_HOST:-}" ]; then
        # Send email if needed
        if [ "${BACKUP_EXIT_CODE}" -eq 0 ]; then
            if [ "${EMAIL_ON_SUCCESS:-0}" = "1" ]; then
                echo "Sending email to confirm successful backup."
                /usr/local/sbin/send-mail-notification "SUCCESS"
            fi
        else
            if [ "${EMAIL_ON_FAILURE:-1}" = "1" ]; then
                echo "Sending email to confirm unsuccessful backup."
                /usr/local/sbin/send-mail-notification "FAILURE"
            fi
        fi
    fi

    if [ -n "$HEALTHCHECKSURL" ]; then
        # We pipe the exit code to healthchecks, if it isn't zero, a warning will fire.
        curl -fsS -m 10 --retry 5 -o /dev/null ${HEALTHCHECKSURL}/${BACKUP_EXIT_CODE}
    fi
elif [ "$CRON_BACKUP_ONLY" = "1" ]; then
    echo "CRON_BACKUP_ONLY=1, skipping container start up initial backup."
elif [ "$CRON_BACKUP_ONLY" != "0" ] && [ "$CRON_BACKUP_ONLY" != "1" ]; then 
    echo "CRON_BACKUP_ONLY set to invalid value, skipping container start up initial backup."
fi

# Set this so backups always happen after the first run via CRON given logic above.
# The date may also be useful for something like a health check if I write it...
# First run touches the file. Backups will set the date.
touch "${lastrunfile}"
