#!/usr/bin/with-contenv bash
# shellcheck shell=bash

source /etc/s6-overlay/s6-rc.d/setup_check/run_include

# We need to build this command in case namespaces are in use.
LISTCMD="proxmox-backup-client snapshot list"
if [ -n "$PBS_DATASTORE_NS" ]; then
    LISTCMD+=" --ns ${PBS_DATASTORE_NS}"
fi
LISTCMD+=" --output-format json"

data=$(${LISTCMD})
host_name=$(hostname)

echo "$data" | jq -r --arg host "$host_name" '
    .[] |
    select(.["backup-id"] == $host) |
    "\(.["backup-type"])/\($host)/\(.["backup-time"] | tonumber | strftime("%Y-%m-%dT%H:%M:%SZ")): \(.files[].filename)"' | 
    awk -F ': ' '
        {
            if (timestamps[$1]) {
                timestamps[$1] = timestamps[$1] "\n\t" $2
            } else {
                timestamps[$1] = "\t" $2
            }
        }
        END {
            for (ts in timestamps) {
                print ts ":"
                print timestamps[ts]
            }
        }'
