#!/usr/bin/expect -f
set random_password [exec openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 64]
spawn proxmox-backup-client key create-master-key
expect "Master Key Password:"
send "$random_password\r"
expect "Verify Password:"
send "$random_password\r"
expect eof
puts "\n### IMPORTANT: New client master key pair encryption key password: $random_password ###"
puts "\n### IMPORTANT: Make sure to backup the master keyfiles and password. ###"