name: Update Submodule proxmox-backup-arm64

on:
  #schedule:
  #  - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y
      
      - name: Run update script
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          chmod +x ./update_submodule.sh
          ./update_submodule.sh
